version: '3.7'

services:
  server:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
    - data:/vol/server
    image: iamdavidmiguelalvarez/budgeting:server
    ports:
    - "8000:8000"
  postgres:
    build: ./postgres
    restart: always
    env_file:
      - .env
    image: iamdavidmiguelalvarez/budgeting:postgres
    volumes:
    - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: